version: '3'

services:
  kv-store:
    build: .
    container_name: kv-store
    mem_limit: 128m
    memswap_limit: 128m
    ports:
      - "5001:5001"
    restart: unless-stopped
    environment:
      - PORT=5001
