version: '3'

services:
  kv-store-1:
    build: .
    container_name: kv-store-1
    mem_limit: 128m
    memswap_limit: 128m
    ports:
      - "5001:5001"
    expose:
      - "5001"
    restart: unless-stopped
    environment:
      - PORT=5001
      - BACKENDS=kv-store-2:5002,kv-store-3:5003
  kv-store-2:
    build: .
    container_name: kv-store-2
    mem_limit: 128m
    memswap_limit: 128m
    ports:
      - "5002:5002"
    expose:
      - "5002"
    restart: unless-stopped
    environment:
      - PORT=5002
      - BACKENDS=kv-store-1:5001,kv-store-3:5003
  kv-store-3:
    build: .
    container_name: kv-store-3
    mem_limit: 128m
    memswap_limit: 128m
    ports:
      - "5003:5003"
    expose:
      - "5003"
    restart: unless-stopped
    environment:
      - PORT=5003
      - BACKENDS=kv-store-1:5001,kv-store-2:5002
  nginx:
    image: nginx:latest
    container_name: nginx-lb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5004:5004"
    depends_on:
      - kv-store-1
      - kv-store-2
      - kv-store-3
    restart: unless-stopped
